# This file was generated by GoReleaser. DO NOT EDIT.
class Accio < Formula
  desc "Accio is a flexible framework for boilerplate code generators"
  homepage "https://github.com/g1ntas/accio"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_macOS-64bit.tar.gz"
    sha256 "6396decf36113381479367c88996df9a7ac314629e71b26ebad367c79d35bf56"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_Linux-64bit.tar.gz"
      sha256 "e13f75502cf66de4165b0561de929892d8df33bf863d330075a356a7a068fa8a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_Linux-ARM64.tar.gz"
        sha256 "56aca16748f3f7ebfea631020e9d0e3722fb3dbb47e2583b34d4ff30e0450337"
      else
      end
    end
  end
  
  depends_on "go"
  depends_on "git" => :optional

  def install
    bin.install "accio"
  end

  test do
    system "#{bin}/accio -v"
  end
end
