# This file was generated by GoReleaser. DO NOT EDIT.
class Accio < Formula
  desc "Accio is a flexible framework for boilerplate code generators"
  homepage "https://github.com/g1ntas/accio"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_macOS-64bit.tar.gz"
    sha256 "5eaf172297675555c63f70b11ec3653b0348aef91fc6c144cae048dcd0bbc8a0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_Linux-64bit.tar.gz"
      sha256 "678e96881dd20d7461631fef3836a3d102b5ec307e49f9063da39874e0e52b92"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/g1ntas/accio/releases/download/v0.1.0/accio_0.1.0_Linux-ARM64.tar.gz"
        sha256 "2025989560f60299d46fea5b5730cdfe43bedf66309e77e0bb3039d62fd37f33"
      else
      end
    end
  end
  
  depends_on "go"
  depends_on "git" => :optional

  def install
    bin.install "accio"
  end

  test do
    system "#{bin}/accio -v"
  end
end
